name: import cert

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy
    steps:
    - name: Install jq and libnss3-tools
      run: apt-get update && apt-get install -y jq libnss3-tools
    - name: Checkout playwright-tests-repo (tests)
      uses: actions/checkout@v4
      with:
        repository: pc-aide/playwright-tests-repo
        path: playwright-tests-repo
    - name: Import cert.crt into Chrome certificate manager
      run: |
        NSSDB_DIR="$HOME/.pki/nssdb"
        mkdir -p "$NSSDB_DIR"
        certutil -d sql:"$NSSDB_DIR" -N --empty-password
        certutil -d sql:"$NSSDB_DIR" -A -t "C,," -n "custom-cert" -i playwright-tests-repo/cert.crt
    - name: Clone Playwright-Intro (config)
      run: git clone https://github.com/pc-aide/Playwright-Intro.git Playwright-Intro
    - name: Copy Playwright config to tests repo
      run: cp Playwright-Intro/playwright.config.ts playwright-tests-repo/playwright.config.ts
    - name: Install dependencies
      run: npm i @playwright/test@1.57.0
      working-directory: playwright-tests-repo
    - name: Run cert check test
      run: xvfb-run -a npx playwright test tests/checkUp-certmgr-chrome.spec.ts --project=chrome --headed
      working-directory: playwright-tests-repo
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: screenshots
        path: 'playwright-tests-repo/*.png'
        retention-days: 30
